name: Build LaTeX

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install TeX Live + Python (for minted)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-cyrillic \
            texlive-science \
            texlive-luatex \
            texlive-xetex \
            python3-pygments \
            latexmk

      - name: Compile PDF with latexmk
        working-directory: tex
        run: |
          latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: trd-pdf
          path: tex/main.pdf
