name: Build LaTeX document

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: trd-pdf
          path: tex/main.pdf
